### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by AG0811** [AG0811/furima-40739#24]
フリマアプリの挙動確認をお願いいたします。

#自身のフリマアプリのURL
https://furima-40739.onrender.com
#出品者用のメールアドレスとパスワード
testa@gmail.com / test123
#購入者用のメールアドレスとパスワード
testb@gmail.com / test123

**Comment by mo1015** [comment]
@AG0811 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されること**
すでに商品が出品されていたため、上記確認ができませんでした。データベースをリセットしてから再提出をお願いいたします。

- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
「家電・スマホ・カメラ」が抜けているため追加しましょう。

- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
都道府県を入力しなくても購入ができてしまいます。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by AG0811** [comment]
上記三点の修正が完了しました。
・データベースのリセット
・ カテゴリーに「家電・スマホ・カメラ」を追加
・ 配送先の都道府県が未入力の場合のバリテーション修正

上記に関しまして、本番環境にて確認をしております。

**Comment by shodai-ito** [comment]
@AG0811 さん、最終課題「FURIMA」の開発、お疲れ様です！

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます！

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by AG0811** [comment]
挙動確認ありがとうございます。
LGTMを確認いたしましたので此方はクローズいたします。
追加機能に関しまして、オリジナルアプリ作成以降に実装してみる予定です。
ご確認ありがとうございました。
